version: "2"

services:
  es:
    image: elasticsearch:5
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data:/usr/share/elasticsearch/data

  es-seed:
    image: elasticsearch:5
    command: /seed/es-seed-data.sh
    volumes:
      - ./seed:/seed
  node-build:
    build:
      context: ./
      dockerfile: ./compose/node/Dockerfile
    command: yarn build
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - es
  #kibana:
  #image: kibana:5
  #links:
  #- elasticsearch
  #ports:
  #- "5601:5601"
  #depends_on:
  #- es
